# Generated by Django 6.0.8 on 2026-09-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_notification_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('enrollment', 'New Enrollment'), ('course_material', 'New Course Material'), ('chat', 'New Chat'), ('feed_comment', 'New Comment')], max_length=20),
        ),
    ]
